name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies
        run: pnpm build

      - name: Test
        run: pnpm test:coverage

      - name: Test
        run: pnpm test:coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.0
